"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Syne } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import { usePathname } from "next/navigation";
import path from "path";
import ThemeProvider from "./provider/ThemeProvider";

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Assisials",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={`${syne.variable}  antialiased`}>
        <ThemeProvider>
          <section className="font-primary">
            {pathname === "/" ? null : <Nav />}
            {children}
            <Footer />
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
